# Generated by Django 5.0.1 on 2024-01-15 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_explicamisto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
